import logging

from fastapi import APIRouter, Depends, HTTPException

from api.dependencies import get_llm
from api.schemas import TitleRequest, TitleResponse, ValidationErrorResponse
from llm.base import LLMClient, Message
from llm.errors import LLMUnavailableError

logger = logging.getLogger(__name__)

router = APIRouter()

SYSTEM_PROMPT = """
You generate short descriptive titles.

Rules:

- return only the title
- no quotes
- no explanations
- respect the character limit
"""


@router.post(
    "/title",
    summary="Generate a title from a prompt",
    response_model=TitleResponse,
    description=(
        "Uses LLM to generate a concise, descriptive title from the given prompt.\n\n"
        "Constraints:\n"
        "- Title is generated by an LLM using a strict system prompt\n"
        "- Title is post-processed to ensure it does not exceed max_length characters\n"
        "- Empty or whitespace-only prompts are rejected with a validation error\n\n"
        "This endpoint is synchronous and returns a single JSON response."
    ),
    responses={
        422: {
            "model": ValidationErrorResponse,
            "content": {
                "application/json": {"example": {"detail": "prompt cannot be blank"}}
            },
        },
        503: {
            "model": ValidationErrorResponse,
            "content": {
                "application/json": {
                    "example": {
                        "detail": "LLM backend unreachable at 'http://localhost:11434'"
                    }
                }
            },
        },
    },
)
def generate_title(
    body: TitleRequest, llm: LLMClient = Depends(get_llm)
) -> TitleResponse:
    """
    Generate a short descriptive title from a user prompt using an LLM.

    Args:
        body: Request body containing the prompt and max_length constraint.
        llm: Injected LLM client used to generate the title.

    Returns:
        TitleResponse: Object containing the generated title.

    Raises:
        HTTPException:
            - 503: If the LLM backend is unavailable or unreachable.

    Behavior:
        - Sends a system prompt to enforce strict title generation rules.
        - Combines system + user message for LLM input.
        - Trims whitespace from LLM output.
        - Enforces max_length constraint by hard truncation.
    """

    messages: list[Message] = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                f"Create a title with maximum {body.max_length} characters.\n\n"
                f"{body.prompt}"
            ),
        },
    ]

    try:
        generated_title = llm.generate(messages=messages).strip()

        # enforce max length
        if len(generated_title) > body.max_length:
            generated_title = generated_title[: body.max_length].rstrip()

        return TitleResponse(title=generated_title)
    except LLMUnavailableError as exc:
        raise HTTPException(
            status_code=503,
            detail=str(exc),
        ) from exc
